### ISSUE TITLE
Specific query?

### ISSUE THREAD

**Issue by JamesParkDev** [Cappuchino/napolitan-bot#2]
Users can choose queries to search for so It's not only limited to "Napolitan" maybe rename bot to "Image-bot"?

Example:

```
QUERY="Food"
```
Translates to `["Food"]`

```
QUERY="Food, Anime"
```
Translates to `["Food", "Anime"]`

Chooses random words each time so first `Food` Then again or it could be `Anime`

**Comment by korewaChino** [comment]
I might add that in the future, but one could just have a custom query in the code and then they have to edit the Google CSE settings too.

**Comment by JamesParkDev** [comment]
Yeah, true, but this makes it easier for people to edit without any prior knowledge of coding. So It's more user-friendly.

**Comment by korewaChino** [comment]
Yea, I will do it.
